name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up venv and install dependencies
        run: |
          python3 -m venv .venv
          .venv/bin/pip install -r requirements.txt

      - name: Run quality checks via Makefile
        run: make all
